### ISSUE TITLE
Can't Decode

### ISSUE THREAD

**Issue by deepak-kiran** [vvHacker007/Steganogrphy#1]
IndexError: Impossible to detect message.

**Comment by baardev** [comment]
I get same also as well

```
Enter the name of video with extension :Embedded_Video.mp4
[INFO] temp directory is created
Traceback (most recent call last):
  File "/home/jw/store/src/Steganography/main.py", line 101, in <module>
    decode_string(input("Enter the name of video with extension :"))
  File "/home/jw/store/src/Steganography/main.py", line 66, in decode_string
    secret_dec=lsb.reveal(f_name)         # Revealing the message inside each string
  File "/home/jw/miniforge3/lib/python3.10/site-packages/stegano/lsb/lsb.py", line 88, in reveal
    if revealer.decode_pixel((col, row)):
  File "/home/jw/miniforge3/lib/python3.10/site-packages/stegano/tools.py", line 205, in decode_pixel
    raise IndexError("Impossible to detect message.")
IndexError: Impossible to detect message.
```

**Comment by vvHacker007** [comment]
@baardev Is it coming for both image and video or just video?

**Comment by baardev** [comment]
It was just the video (I think... it was a while back and I no longer use that tool)

**Comment by vvHacker007** [comment]
@baardev might be some dependency issue, have you tried using the same version of stegano?

**Comment by y1xing** [comment]
Hi, what is the version of stegano needed?

**Comment by Iqbalanataa** [comment]
when i try to reveal video i got this error, how to fix this one?

![Screenshot 2024-01-20 212642](https://github.com/vvHacker007/Steganography/assets/49528835/644a35ca-abe9-4192-a8d3-afd222e44e71)
